#!/usr/bin/env ruby

require 'fileutils'

OLD_REF = "6.16.0"
NEW_REF = "OHAI-412"

OHAI_CLONE = File.expand_path("../../ohai/", __FILE__)
OHAI_BIN = File.expand_path("bin/ohai", OHAI_CLONE)

DATA_ROOT = File.expand_path("../../test-result/", __FILE__)

uname = `uname -s -r`
platform_descriptor = if uname.empty?
                        "unknown"
                      else
                        uname.strip.gsub(/\s/, "-")
                      end

run_id = Time.now.to_i.to_s

DATA_DIR = File.join(DATA_ROOT, platform_descriptor, run_id)
FileUtils.mkdir_p(DATA_DIR)

Dir.chdir(OHAI_CLONE) do
  system("git checkout #{OLD_REF}")
  system("#{OHAI_BIN} -v")
  puts("#{OHAI_BIN} -lerror > #{DATA_DIR}/old_ohai.json")
  system("#{OHAI_BIN} -lerror > #{DATA_DIR}/old_ohai.json")

  system("git checkout #{NEW_REF}")
  system("#{OHAI_BIN} -v")
  puts("#{OHAI_BIN} -lerror > #{DATA_DIR}/new_ohai.json")
  system("#{OHAI_BIN} -lerror > #{DATA_DIR}/new_ohai.json")
end
